name: foliate
grade: stable
adopt-info: foliate
license: GPL-3.0+
base: core22
confinement: strict
compression: lzo
architectures:
  - build-on: [amd64]
    build-for: [amd64]


apps:
  foliate:
    command: usr/bin/com.github.johnfactotum.Foliate
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - removable-media
    slots:
      - dbus-daemon
    common-id: com.github.johnfactotum.Foliate

parts:
  foliate:
    plugin: meson
    source: https://github.com/johnfactotum/foliate.git
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    meson-parameters: [--prefix=/snap/foliate/current/usr]
    build-packages:
      - git
      - build-essential
      - xmlstarlet  
    organize:
      snap/foliate/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.johnfactotum.Foliate.appdata.xml]
  tts:
    plugin: nil
    stage-packages:
      - espeak-ng
      - speech-dispatcher-espeak-ng
      

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data:
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/espeak-ng-data
  /usr/bin/gjs:
    symlink: $SNAP/gnome-platform/usr/bin/gjs
