name: foliate-gtk
base: core22
adopt-info: foliate-gtk
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64


slots:
  foliate-gtk:
    interface: dbus
    bus: session
    name: com.github.johnfactotum.Foliate

apps:
  foliate-gtk:
    command: usr/bin/com.github.johnfactotum.Foliate
    extensions: [gnome]
    common-id: com.github.johnfactotum.Foliate
    desktop: usr/share/applications/com.github.johnfactotum.Foliate.desktop
    
parts:
  foliate-gtk:
    source: https://github.com/johnfactotum/foliate/releases/download/2.6.4/com.github.johnfactotum.foliate_2.6.4_all.deb
    plugin: dump
    stage-packages:
      - gjs
      - libgjs0g
      - libmozjs-91-0
    
